import { CardTypes, ICard } from "./interfaces";

export const initCards: ICard[] = [
  {
    id: 1,
    type: CardTypes.design,
    name: "SOFA",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image1.jpg",
  },
  {
    id: 2,
    type: CardTypes.branding,
    name: "Keyboard",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image2.jpg",
  },
  {
    id: 3,
    type: CardTypes.illustration,
    name: "Work Media",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image3.jpg",
  },
  {
    id: 4,
    type: CardTypes.motion,
    name: "DDDdone",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image4.jpg",
  },
  {
    id: 5,
    type: CardTypes.design,
    name: "Abstract",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image5.jpg",
  },
  {
    id: 6,
    type: CardTypes.branding,
    name: "HandP",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image6.jpg",
  },
  {
    id: 7,
    type: CardTypes.motion,
    name: "Architect",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image7.jpg",
  },
  {
    id: 8,
    type: CardTypes.design,
    name: "CalC",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image8.jpg",
  },
  {
    id: 9,
    type: CardTypes.branding,
    name: "Sport",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image9.jpg",
  },
  {
    id: 10,
    type: CardTypes.design,
    name: "SOFA 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image1.jpg",
  },
  {
    id: 11,
    type: CardTypes.branding,
    name: "Keyboard 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image2.jpg",
  },
  {
    id: 12,
    type: CardTypes.illustration,
    name: "Work Media 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image3.jpg",
  },
  {
    id: 13,
    type: CardTypes.motion,
    name: "DDDdone 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image4.jpg",
  },
  {
    id: 14,
    type: CardTypes.design,
    name: "Abstract 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image5.jpg",
  },
  {
    id: 15,
    type: CardTypes.branding,
    name: "HandP 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image6.jpg",
  },
  {
    id: 16,
    type: CardTypes.motion,
    name: "Architect 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image7.jpg",
  },
  {
    id: 17,
    type: CardTypes.design,
    name: "CalC 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image8.jpg",
  },
  {
    id: 18,
    type: CardTypes.branding,
    name: "Sport 2",
    isSelected: false,
    imageSrc: "http://localhost:5000/images/image9.jpg",
  },
];
